openapi: 3.0.0
info:
  title: Store api 
  description: ecommerce store api 
  version: 1.0.0 

servers:
  - url: "http://localhost:4000/api/{version}"
    description: localhost version of the app 
    variables: 
     version:
      enum:
        - v1
        - v2
     
